name: aoh

services:
    traefik:
        image: traefik:v3.6.1
        privileged: true
        restart: on-failure
        deploy:
            restart_policy:
                delay: 10s
        command:
            - --api=true
            - --api.dashboard=true
            - --api.insecure=true
            - --providers.docker=true
            - --providers.docker.exposedByDefault=false
            - --entrypoints.web.address=:80
            - --entrypoints.sdstcp.address=:5333
        labels:
            - traefik.enable=true
            - traefik.http.routers.traefik.rule=Host(`traefik.${DEV_DOMAIN}`)
            - traefik.http.routers.traefik.service=api@internal
            - traefik.http.routers.traefik.entrypoints=web
            - traefik.http.middlewares.permissive-headers.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH,HEAD
            - traefik.http.middlewares.permissive-headers.headers.accesscontrolallowheaders=*
            - traefik.http.middlewares.permissive-headers.headers.accesscontrolalloworiginlist=*
            - traefik.http.middlewares.permissive-headers.headers.accesscontrolallowcredentials=true
            - traefik.http.middlewares.permissive-headers.headers.accesscontrolmaxage=100
            - traefik.http.middlewares.permissive-headers.headers.addvaryheader=true
            - traefik.entrypoints.web.forwardedHeaders.insecure=true
        volumes:
            - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
        ports:
            - ${TRAEFIK_HTTP_PORT:-80}:80
            - ${SDS_TCP_PORT:-5333}:5333
